//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalogo_de_Cuentas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Catalogo_de_Cuentas()
        {
            this.Movimiento_Contable = new HashSet<Movimiento_Contable>();
        }
    
        public int cod_catalogo { get; set; }
        public string Nombre_de_cataCuenta { get; set; }
        public string Descripcion { get; set; }
        public int Cod_tipocu { get; set; }
        public string Transacciones { get; set; }
        public Nullable<int> Nivel { get; set; }
        public Nullable<int> Balance { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimiento_Contable> Movimiento_Contable { get; set; }
        public virtual Tipo_de_Cuenta Tipo_de_Cuenta { get; set; }
    }
}
