//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_de_Cuenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tipo_de_Cuenta()
        {
            this.Catalogo_de_Cuentas = new HashSet<Catalogo_de_Cuentas>();
        }
    
        public int Cod_tipocu { get; set; }
        public string Nombre_de_Cuenta { get; set; }
        public string Descripcion { get; set; }
        public string Origen { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalogo_de_Cuentas> Catalogo_de_Cuentas { get; set; }
    }
}
